# Generated by Django 3.2 on 2021-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelart',
            name='file',
            field=models.FilePathField(path='images'),
        ),
    ]
